"""IndexManager -- the sole gateway onto Index data (mirrors Section/
Agent/Pipeline/Vault/Template Manager's own "one real gateway" rule). An
Index is a real, user-defined, scoped vault index: which Work/ folders,
which tags, how deep, where the built output lands, and a real Hermes
cron job (created via HermesCli's own `hermes cron create --script
--no-agent`, verified live 2026-08-28 against the real installed CLI)
that rebuilds it on a real schedule.

Mechanism, confirmed live before building this (2026-08-28, a real
disposable cron job, immediately removed): a `--no-agent --script` job
gets ZERO argv and ZERO env passthrough -- a bare `python <script>`
invocation, nothing else. This is why the deployed per-Index script
(`_render_stub`) can't take parameters directly; it bakes in only its
own INDEX_ID plus the app's current DATA_PATH/VAULT_PATH, and reads its
own real Index.json at run time for folders/tags/depth/storage_path --
so updating those fields alone needs no script redeployment.

The actual build engine is `index_builder_lib.py` (Hermes-Provisioning/
skills/vault-rebuild/vault-index/scripts/) -- a generalization of the
existing, single, global `build_vault_index.py`'s own logic (folders/
tags/depth become real parameters instead of "every folder, unlimited
depth, no tag filter"). Deployed as a real file copy (never hand-
duplicated) into whichever profile's own scripts/ dir owns this Index's
cron job, alongside a copy of vault_manager.py for its read_note()
sibling import.

Raw I/O (2026-08-28 layering correction) lives entirely in
`data_access/indexes.py` -- this file holds zero raw file calls, only
entity-shaping, cron orchestration, and the deployed script's own text
composition (deciding WHAT the script says is business logic; writing
it to disk is not).
"""
from __future__ import annotations

from datetime import datetime, timezone

from app.business.core.index.index import Index
from app.business.hermes.client import get_client
from app.config import settings
from app.data_access import indexes as indexes_data
from app.obsidian.tags import tag_slug


class IndexCronCreationError(Exception):
    pass


class IndexNotFoundError(Exception):
    pass


class IndexManager:
    def _cron_status(self, cron_job_id: str | None, cron_profile_id: str | None) -> dict:
        if cron_job_id is None:
            return {}
        job = get_client().cron.get_cron_job(cron_job_id, cron_profile_id)
        if job is None:
            return {}
        return {
            "cron_enabled": job.enabled,
            "cron_schedule_display": job.schedule_display,
            "cron_last_run_at": job.last_run_at,
            "cron_next_run_at": job.next_run_at,
            "cron_last_status": job.last_status,
        }

    def _to_index(self, index_id: str, data: dict) -> Index:
        cron_job_id = data.get("cron_job_id")
        cron_profile_id = data.get("cron_profile_id")
        return Index(
            id=index_id, name=data.get("name") or index_id,
            folders=list(data.get("folders") or []),
            tags=list(data.get("tags") or []),
            depth=data.get("depth"),
            storage_path=data.get("storage_path", ""),
            schedule=data.get("schedule", ""),
            created_at=data.get("created_at", ""),
            updated_at=data.get("updated_at"),
            cron_profile_id=cron_profile_id,
            cron_job_id=cron_job_id,
            **self._cron_status(cron_job_id, cron_profile_id),
        )

    def get_all(self) -> list[Index]:
        indexes = []
        for index_id in indexes_data.list_index_ids():
            try:
                data = indexes_data.read_index_json(index_id)
            except (OSError, ValueError):
                continue
            indexes.append(self._to_index(index_id, data))
        return indexes

    def get_by_id(self, index_id: str) -> Index | None:
        try:
            data = indexes_data.read_index_json(index_id)
        except (OSError, ValueError):
            return None
        return self._to_index(index_id, data)

    def _render_stub(self, index_id: str) -> str:
        """The real per-Index script content -- see the module docstring
        for why it can't just take CLI args. `!r` on every baked-in value
        keeps this a plain, safe Python literal regardless of what real
        path separators/characters DATA_PATH/VAULT_PATH contain (Windows
        backslashes included)."""
        return (
            '"""Auto-generated by IndexManager -- do not hand-edit; regenerated on\n'
            "every create()/update() for this Index. Reads its own real Index.json\n"
            "definition at run time (folders/tags/depth/storage_path), so a change\n"
            "to those alone needs no redeployment -- only DATA_PATH/VAULT_PATH/\n"
            'INDEX_ID here going stale would.\n"""\n'
            "import json\n"
            "import sys\n"
            "from pathlib import Path\n\n"
            "sys.path.insert(0, str(Path(__file__).parent))\n"
            "from index_builder_lib import build_index, write_index\n\n"
            f"INDEX_ID = {index_id!r}\n"
            f"DATA_PATH = Path({str(settings.second_brain_data_path)!r})\n"
            f"VAULT_PATH = Path({str(settings.vault_path)!r})\n\n"
            'definition = json.loads((DATA_PATH / "data" / "Indexes" / INDEX_ID / "Index.json").read_text(encoding="utf-8"))\n'
            'folders = definition.get("folders") or None\n'
            'tags = definition.get("tags") or None\n'
            'depth = definition.get("depth")\n'
            'storage_path = Path(definition["storage_path"])\n\n'
            "result = build_index(VAULT_PATH, folders=folders, tags=tags, depth=depth)\n"
            "summary = write_index(storage_path, result)\n"
            'print(json.dumps({"index_id": INDEX_ID, **summary}, ensure_ascii=False))\n'
        )

    def create(
        self, name: str, *, schedule: str, folders: list[str] | None = None,
        tags: list[str] | None = None, depth: int | None = None,
        storage_path: str | None = None, cron_profile_id: str | None = None,
    ) -> Index:
        """Deploys the real build engine + this Index's own stub script,
        writes its definition, then creates the real Hermes cron job --
        in that order, so the job never fires against a script/
        definition that isn't there yet. Raises IndexCronCreationError
        (definition is still written either way -- retry-able) if the
        real `hermes cron create` call doesn't come back with a real
        job id."""
        index_id = tag_slug(name)
        resolved_storage_path = storage_path or str(
            settings.second_brain_data_path / "data" / "Indexes" / index_id / "output.json"
        )
        now = datetime.now(timezone.utc).isoformat()

        indexes_data.deploy_index_builder(cron_profile_id)
        indexes_data.write_index_script(index_id, cron_profile_id, self._render_stub(index_id))

        definition = {
            "id": index_id, "name": name,
            "folders": folders or [], "tags": tags or [], "depth": depth,
            "storage_path": resolved_storage_path, "schedule": schedule,
            "created_at": now, "updated_at": None,
            "cron_profile_id": cron_profile_id, "cron_job_id": None,
        }
        indexes_data.write_index_json(index_id, definition)

        job_id, output = get_client().cli.create_cron_job(
            schedule, name=f"index-{index_id}", script=f"index_{index_id}.py", no_agent=True,
        )
        if job_id is None:
            raise IndexCronCreationError(output)
        definition["cron_job_id"] = job_id
        indexes_data.write_index_json(index_id, definition)

        return self.get_by_id(index_id)

    def register_existing(
        self, index_id: str, name: str, *, cron_job_id: str, cron_profile_id: str | None,
        schedule: str, folders: list[str] | None = None, tags: list[str] | None = None,
        depth: int | None = None, storage_path: str = "",
    ) -> Index:
        """Brings an ALREADY-REAL cron job under this Manager's own
        tracking (operator, 2026-08-28: "the vault index rebuild is an
        index already, it is one of the indexes that the system need to
        be aware of") -- writes only the definition, linking to the
        existing real cron_job_id. Never creates, edits, or removes a
        real cron job, never deploys/overwrites a script -- the job
        keeps running exactly as it already does."""
        now = datetime.now(timezone.utc).isoformat()
        definition = {
            "id": index_id, "name": name,
            "folders": folders or [], "tags": tags or [], "depth": depth,
            "storage_path": storage_path, "schedule": schedule,
            "created_at": now, "updated_at": None,
            "cron_profile_id": cron_profile_id, "cron_job_id": cron_job_id,
        }
        indexes_data.write_index_json(index_id, definition)
        return self.get_by_id(index_id)

    def update(
        self, index_id: str, *, name: str | None = None, folders: list[str] | None = None,
        tags: list[str] | None = None, depth: int | None = None,
        storage_path: str | None = None, schedule: str | None = None,
    ) -> Index | None:
        """`None` (omitted) = leave unchanged for every field, same
        convention every other Manager's own update() already uses.
        Editing `schedule` also edits the real cron job (if one exists)
        -- every other field is definition-only, picked up by the
        deployed stub's own next real run without any redeployment."""
        try:
            data = indexes_data.read_index_json(index_id)
        except (OSError, ValueError):
            return None

        if name is not None:
            data["name"] = name
        if folders is not None:
            data["folders"] = folders
        if tags is not None:
            data["tags"] = tags
        if depth is not None:
            data["depth"] = depth
        if storage_path is not None:
            data["storage_path"] = storage_path
        if schedule is not None:
            data["schedule"] = schedule
            cron_job_id = data.get("cron_job_id")
            if cron_job_id is not None:
                get_client().cli.edit_cron_job(cron_job_id, schedule=schedule)

        data["updated_at"] = datetime.now(timezone.utc).isoformat()
        indexes_data.write_index_json(index_id, data)
        return self.get_by_id(index_id)

    def delete(self, index_id: str) -> dict:
        """Removes the real cron job, the built output file, the
        deployed stub script, and the definition -- in that order, so a
        failure partway through never leaves the cron job pointing at a
        script/definition that's already gone. Never raises for an
        already-deleted/unknown index -- {"deleted": False} instead
        (ADR-014's own result-dict convention)."""
        index = self.get_by_id(index_id)
        if index is None:
            return {"deleted": False}
        if index.cron_job_id is not None:
            get_client().cli.remove_cron_job(index.cron_job_id)
        indexes_data.delete_output_path(index.storage_path)
        indexes_data.delete_index_script(index_id, index.cron_profile_id)
        indexes_data.delete_index_definition(index_id)
        return {"deleted": True}
