"""AgentManager -- the ONLY door onto Agent data (mirrors SectionManager's
own "one real gateway" rule). Composes a real Agent from several genuinely
separate real sources -- there is no single owning file the way
section_registry.py was for Section:

- Hermes itself (`HermesProfiles`, app/hermes/profiles.py) -- name/
  description/model/reasoning_effort/skills/the real SOUL.md text. This
  is Hermes' own data; Second Brain never fabricates it.
- The Registry (`data_access/registry/loader.py`, REQ-SB-80) --
  section_id/type/is_background_agent/depends_on, once an agent has been
  migrated into the data/ tree. Falls through to the same worker/Data
  Gatherer/no-deps/not-background defaults agents_map_adapter.py's old
  hardcoded dicts always used, for an agent not yet migrated.
- `agent_visual_registry.py` -- icon/color overrides. Deliberately NOT
  folded in here yet (operator: "Agents will have more than one file") --
  this Manager composes it, same as agents_map_adapter.py already does,
  rather than absorbing it.

Fields with no real backing store yet (`working_mode` beyond the single
"autonomous" default) are left at an honest, undecorated default rather
than fabricated -- same discipline agents_map_adapter.py's own module
docstring already committed to.

Write side (create/update/delete): real Hermes-side operations
(`HermesClient.create_profile`/`delete_profile`/`describe_profile`,
`HermesProfiles.update`/`write_soul`) already existed as library
primitives -- unused anywhere until now. The ONE genuinely new piece is
the Registry-side `Agent.json`/`soul.md` writer -- nothing in the app
ever wrote these before (the loader only ever read them; the only prior
writer was a one-off migration script), so `_write_registry_agent`
below is new, not a migration of existing logic the way
section_manager.py's writers were. `Agent.json` is ONE file (2026-08-28,
operator: "we should have one Json file describing the Agent") --
id/name/type/is_background_agent/depends_on/provider_id/skill_ids plus
icon/color, no separate Agent-visual.json anymore; `agent_visual_registry.py`'s
own Registry-mirror write updates the same file's icon/color keys in
place instead of writing a second file. The Registry's own lowercase
`soul.md` has no real reader anywhere (grepped before writing this) --
it exists purely because loader.py's own _load_one_agent is fail-loud on
a missing/empty one, so this Manager treats it as a one-way pushed
MIRROR of the real Hermes SOUL.md (same shape as section_manager.py's
own Section.json mirror), never a second source of truth.
`prompt`+`guardrails`+`scope` compose into that ONE real SOUL.md write
(`_soul_text`) -- confirmed by the operator: both guardrails and scope
get woven into the real SOUL.md text, not stored as separate Hermes-side
fields.
"""
from __future__ import annotations

import json
import shutil

from app.business import agent_visual_registry
from app.business.core.agents.agent import Agent
from app.business.core.sections.section_manager import SectionManager
from app.business.hermes.client import HermesAgent, get_client
from app.data_access.registry import loader as registry_loader
from app.data_access.registry.schemas import Agent as RegistryAgent

_FALLBACK_SECTION_NAME = "Data Gatherer"
_FALLBACK_WORKING_MODE = "autonomous"
_FALLBACK_MANAGED_BY = "hermes"
_SPECIALISTS_BEGIN = "<!-- BEGIN SPECIALISTS (auto-generated by AgentManager -- do not hand-edit) -->"
_SPECIALISTS_END = "<!-- END SPECIALISTS -->"


class AgentManager:
    def __init__(self) -> None:
        self._section_manager = SectionManager()

    def _registry_agent(self, agent_id: str) -> RegistryAgent | None:
        registry = registry_loader.get_registry()
        return registry.agents.get(agent_id) if registry is not None else None

    def _section_id(self, agent_id: str, registry_agent: RegistryAgent | None) -> str:
        if registry_agent is not None and registry_agent.section_id is not None:
            return registry_agent.section_id
        # Not yet migrated -- same real fallback agents_map_adapter.py's
        # old hardcoded dicts always used, resolved through SectionManager
        # (idempotent-collapse-on-collision, always safe) rather than a
        # bare string literal.
        for section in self._section_manager.get_all():
            if section.name == _FALLBACK_SECTION_NAME:
                return section.id
        return self._section_manager.create(_FALLBACK_SECTION_NAME).id

    def _to_agent(self, hermes_agent: HermesAgent) -> Agent:
        registry_agent = self._registry_agent(hermes_agent.id)
        visual = agent_visual_registry.get_agent_visual(hermes_agent.id)
        return Agent(
            id=hermes_agent.id,
            name=registry_agent.config.name if registry_agent is not None else hermes_agent.name,
            description=hermes_agent.description or None,
            type=registry_agent.config.type if registry_agent is not None else "worker",
            section_id=self._section_id(hermes_agent.id, registry_agent),
            is_background_agent=(
                registry_agent.config.is_background_agent if registry_agent is not None else False
            ),
            icon=visual.get("icon") or hermes_agent.icon,
            color=visual.get("color"),
            working_mode=_FALLBACK_WORKING_MODE,
            managed_by=_FALLBACK_MANAGED_BY,
            model=hermes_agent.model or None,
            reasoning_effort=hermes_agent.reasoning_effort or None,
            prompt=get_client().profiles.read_soul(hermes_agent.id),
            guardrails=None,
            scope={"folders": [], "tags": []},
            skill_ids=[skill.id for skill in hermes_agent.skills],
            depends_on=registry_agent.config.depends_on if registry_agent is not None else [],
        )

    def get_all(self, *, exclude_types: list[str] | None = None) -> list[Agent]:
        """`exclude_types` is real business logic (which kinds of Agent a
        given caller wants), not something callers should reimplement as
        their own client-side filter -- e.g. the Agents Map's own `GET
        /agents` passes `exclude_types=["hub"]` so a Hub (already
        rendered as its Section's own SectionHub center node) is never
        even in the response, rather than the frontend filtering one out
        after the fact."""
        agents = [self._to_agent(agent) for agent in get_client().profiles.get_all()]
        if exclude_types:
            agents = [a for a in agents if a.type not in exclude_types]
        return agents

    def get_by_id(self, agent_id: str) -> Agent | None:
        hermes_agent = get_client().profiles.find_by_id(agent_id)
        if hermes_agent is None:
            return None
        return self._to_agent(hermes_agent)

    def get_section_agents(
        self, section_id: str, *, include_types: list[str] | None = None, exclude_types: list[str] | None = None,
    ) -> list[Agent]:
        """Every real Agent in one Section, optionally filtered by type
        -- `include_types` and `exclude_types` are mutually exclusive
        (pass at most one; `include_types` wins if both are given).
        General-purpose (not built for one specific caller) -- e.g. "give
        me this Section's real specialists" is
        `get_section_agents(section_id, exclude_types=["hub"])`."""
        agents = [a for a in self.get_all() if a.section_id == section_id]
        if include_types:
            return [a for a in agents if a.type in include_types]
        if exclude_types:
            return [a for a in agents if a.type not in exclude_types]
        return agents

    def get_expert_agents(self) -> list[Agent]:
        """Every real `type == "expert"` Agent, excluding Hubs by
        construction (a Hub is never typed `expert`). General-purpose --
        Cockpit's own moderator (`business/cockpit/moderator.py`) needs
        exactly this ("which of my real agents can answer a domain
        question") for question routing/expert-matching, rather than
        pulling the full roster and filtering `type != "expert"` itself
        the way it used to."""
        return [a for a in self.get_all() if a.type == "expert"]

    def regenerate_specialists_section(self, agent_id: str) -> Agent | None:
        """Explicit, separate call -- NEVER triggered automatically inside
        create/update (operator: "since we will be changing depends_on
        sometimes, specially when we are customizing" -- too disruptive
        to rewrite a parent's real prompt on every tweak).

        `depends_on` has no real Hermes backing (confirmed against the
        real `hermes peer --help` -- that's cross-gateway only); every
        real same-install relay this session hand-built works because a
        `terminal(hermes -p <profile> chat ...)` instruction was
        hand-written into the PARENT's own SOUL.md. This generates that
        instruction instead of relying on it being written by hand.

        Real, confirmed direction (live data, not assumed): the CHILD's
        `depends_on` points at the PARENT
        (`compass-pricing-expert.depends_on == ['compass-expert']`), but
        the relay text belongs on the PARENT's SOUL.md -- so this finds
        every agent whose `depends_on` includes `agent_id` (this agent's
        real "specialists"), not the other way around.

        Idempotent -- the generated block is wrapped in
        `_SPECIALISTS_BEGIN`/`_SPECIALISTS_END` markers so a re-run
        replaces its own prior block instead of duplicating it, and a
        parent left with zero real children has the block removed
        entirely rather than left stale."""
        agent = self.get_by_id(agent_id)
        if agent is None:
            return None
        children = sorted(
            (a for a in self.get_all() if agent_id in a.depends_on), key=lambda a: a.id,
        )
        current_prompt = agent.prompt or f"You are {agent.name}."
        new_prompt = self._apply_specialists_block(current_prompt, children)
        if new_prompt == current_prompt:
            return agent
        return self.update(agent_id, prompt=new_prompt)

    def _specialists_block_text(self, children: list[Agent]) -> str | None:
        if not children:
            return None
        bullets = "\n".join(
            f"- **`{child.id}`** -- {child.description or child.name}" for child in children
        )
        return (
            f"{_SPECIALISTS_BEGIN}\n"
            "## Your own specialists\n\n"
            "Each is a separate Hermes profile -- reach one with:\n\n"
            "```\n"
            'terminal(command="hermes -p <profile> chat -q \\"<the real question, in your own words>\\" '
            '-Q --create-if-missing -c \\"<a session name for this thread>\\"")\n'
            "```\n\n"
            "Reuse the same `-c` session name across a multi-turn exchange so context carries over. "
            "Report their reply back in your own words -- don't paste raw output.\n\n"
            f"{bullets}\n"
            f"{_SPECIALISTS_END}"
        )

    def _apply_specialists_block(self, prompt: str, children: list[Agent]) -> str:
        block = self._specialists_block_text(children)
        start = prompt.find(_SPECIALISTS_BEGIN)
        end = prompt.find(_SPECIALISTS_END)
        has_existing_block = start != -1 and end != -1
        if has_existing_block:
            end += len(_SPECIALISTS_END)
            before, after = prompt[:start].rstrip(), prompt[end:].lstrip()
            if block is None:
                # No real children left -- remove the block entirely
                # rather than leaving a stale one behind.
                return f"{before}\n\n{after}".strip() if after else before
            return f"{before}\n\n{block}\n\n{after}".strip() if after else f"{before}\n\n{block}"
        if block is None:
            return prompt
        return f"{prompt.rstrip()}\n\n{block}"

    def _agent_dir(self, agent_id: str, *, section_id: str, is_background_agent: bool):
        root = registry_loader.data_root()
        if is_background_agent:
            return root / "Background" / "Agents" / agent_id
        return root / "Sections" / section_id / "Agents" / agent_id

    def _soul_text(
        self, name: str, prompt: str | None, guardrails: str | None, scope: dict | None,
    ) -> str:
        """Composes prompt+guardrails+scope into ONE real SOUL.md text
        (operator: both guardrails and scope get woven in, not stored
        separately). Never empty -- loader.py's own _load_one_agent is
        fail-loud on an empty soul.md, so a never-set prompt falls back
        to a minimal, honest identity line rather than an empty file."""
        parts = [prompt.strip() if prompt else f"You are {name}."]
        if guardrails and guardrails.strip():
            parts.append(f"## Guardrails\n\n{guardrails.strip()}")
        folders = (scope or {}).get("folders") or []
        tags = (scope or {}).get("tags") or []
        if folders or tags:
            scope_lines = []
            if folders:
                scope_lines.append(f"Folders: {', '.join(folders)}")
            if tags:
                scope_lines.append(f"Tags: {', '.join(tags)}")
            parts.append("## Scope\n\n" + "\n".join(scope_lines))
        return "\n\n".join(parts)

    def _write_registry_agent(
        self, agent_id: str, *, section_id: str, is_background_agent: bool,
        config: dict, icon: str | None, color: str | None, soul_text: str,
    ) -> None:
        """The one genuinely new writer here -- nothing in the app ever
        wrote Agent.json/soul.md before (loader.py only ever reads them).
        Mirrors section_manager.py's own _write_registry_section_json
        shape: a plain, additive file write, picked up by RegistryLoader's
        own hot-reload poll (~2s). ONE `Agent.json` file, not a separate
        Agent-config.json/Agent-visual.json pair (operator: "we should
        have one Json file describing the Agent") -- icon/color are just
        two more keys on the same config dict."""
        agent_dir = self._agent_dir(agent_id, section_id=section_id, is_background_agent=is_background_agent)
        agent_dir.mkdir(parents=True, exist_ok=True)
        (agent_dir / "Agent.json").write_text(
            json.dumps({**config, "icon": icon, "color": color}, indent=2), encoding="utf-8",
        )
        (agent_dir / "soul.md").write_text(soul_text, encoding="utf-8")

    def create(
        self,
        agent_id: str,
        *,
        name: str,
        section_id: str,
        type: str,  # "worker" | "producer" | "expert" | "hub"
        is_background_agent: bool = False,
        depends_on: list[str] | None = None,
        description: str | None = None,
        prompt: str | None = None,
        guardrails: str | None = None,
        scope: dict | None = None,
        clone_from: str = "default",
    ) -> Agent:
        """Real Hermes-side profile creation (`hermes profile create
        --clone`, via HermesClient.create_profile -- a real library
        primitive that existed unused until now) plus the Registry-side
        Agent.json/soul.md this agent needs to be visible on the map at all. `clone_from` defaults to "default" (the
        Primary profile) -- every real specialist built by hand this
        session was cloned from an existing profile, never created from
        nothing. `depends_on` defaults to the Section's own Hub agent
        (its `fallback_agent_id`) when omitted -- every new agent is a
        specialist of its Section's Hub by default, matching the real
        relay-chain shape already hand-built for compass-expert/
        azure-expert's own children. Never applied when creating the Hub
        itself (`type == "hub"`, would depend on its own not-yet-set id)
        or when the Section has no Hub yet (falls through to `[]`,
        same as before)."""
        if depends_on is None and type != "hub":
            section = self._section_manager.get_by_id(section_id)
            if section is not None and section.fallback_agent_id:
                depends_on = [section.fallback_agent_id]
        get_client().create_profile(agent_id, clone=True, clone_from=clone_from, description=description)
        soul_text = self._soul_text(name, prompt, guardrails, scope)
        get_client().profiles.write_soul(agent_id, soul_text)
        self._write_registry_agent(
            agent_id, section_id=section_id, is_background_agent=is_background_agent,
            config={
                "id": agent_id, "name": name, "type": type,
                "is_background_agent": is_background_agent,
                "depends_on": depends_on or [], "provider_id": None, "skill_ids": [],
            },
            icon=None, color=None, soul_text=soul_text,
        )
        return self.get_by_id(agent_id)

    def update(
        self,
        agent_id: str,
        *,
        name: str | None = None,
        description: str | None = None,
        section_id: str | None = None,
        type: str | None = None,
        is_background_agent: bool | None = None,
        depends_on: list[str] | None = None,
        icon: str | None = None,
        color: str | None = None,
        model: str | None = None,
        reasoning_effort: str | None = None,
        prompt: str | None = None,
        guardrails: str | None = None,
        scope: dict | None = None,
    ) -> Agent | None:
        """Same omitted-vs-explicit convention as SectionManager.update:
        `None` (field omitted) = leave unchanged. Dispatches to whichever
        real system actually owns the field -- Hermes for description/
        model/reasoning_effort/prompt+guardrails+scope, the Registry for
        name/section_id/type/is_background_agent/depends_on, visual
        registry for icon/color -- never a single flat write."""
        current = self.get_by_id(agent_id)
        if current is None:
            return None

        if description is not None:
            get_client().describe_profile(agent_id, text=description, overwrite=True)

        if model is not None or reasoning_effort is not None:
            patch: dict = {}
            if model is not None:
                patch.setdefault("model", {})["default"] = model
            if reasoning_effort is not None:
                patch.setdefault("agent", {})["reasoning_effort"] = reasoning_effort
            get_client().profiles.update(agent_id, patch)

        new_section_id = section_id if section_id is not None else current.section_id
        new_is_background = is_background_agent if is_background_agent is not None else current.is_background_agent
        new_name = name if name is not None else current.name
        new_type = type if type is not None else current.type
        new_depends_on = depends_on if depends_on is not None else current.depends_on
        new_icon = icon if icon is not None else current.icon
        new_color = color if color is not None else current.color
        new_prompt = prompt if prompt is not None else current.prompt
        new_guardrails = guardrails if guardrails is not None else current.guardrails
        new_scope = scope if scope is not None else current.scope

        moved = (new_section_id, new_is_background) != (current.section_id, current.is_background_agent)
        registry_changed = moved or any(
            v is not None for v in (name, type, is_background_agent, depends_on, section_id)
        )
        soul_changed = any(v is not None for v in (prompt, guardrails, scope))

        if icon is not None or color is not None:
            agent_visual_registry.set_agent_visual(agent_id, icon=icon, color=color)
            new_icon = agent_visual_registry.get_agent_visual(agent_id).get("icon") or new_icon
            new_color = agent_visual_registry.get_agent_visual(agent_id).get("color")

        if registry_changed or soul_changed:
            # Captured BEFORE the new location is written -- section_id/
            # is_background_agent aren't stored fields, they're derived
            # from the folder path itself (Sections/<id>/Agents/<agent>/
            # vs Background/Agents/<agent>/), so moving either one means
            # relocating the whole folder, not editing a field in place.
            old_dir = registry_loader.agent_data_dir(agent_id) if moved else None

            soul_text = self._soul_text(new_name, new_prompt, new_guardrails, new_scope)
            if soul_changed:
                get_client().profiles.write_soul(agent_id, soul_text)
            self._write_registry_agent(
                agent_id, section_id=new_section_id, is_background_agent=new_is_background,
                config={
                    "id": agent_id, "name": new_name, "type": new_type,
                    "is_background_agent": new_is_background,
                    "depends_on": new_depends_on, "provider_id": None, "skill_ids": current.skill_ids,
                },
                icon=new_icon, color=new_color, soul_text=soul_text,
            )
            if old_dir is not None and old_dir.is_dir():
                shutil.rmtree(old_dir, ignore_errors=True)

        return self.get_by_id(agent_id)

    def delete(self, agent_id: str) -> dict:
        """Real Hermes-side profile deletion (HermesClient.delete_profile
        -- a real library primitive that existed unused until now). Also
        removes this agent's own Registry folder if it has one -- never
        leaves an orphaned Agent.json/soul.md behind for a profile
        that no longer exists. No blocking/dependency check yet (unlike
        Section's delete) -- flagged as follow-up, not silently assumed
        safe."""
        agent_dir = registry_loader.agent_data_dir(agent_id)
        get_client().delete_profile(agent_id)
        if agent_dir is not None and agent_dir.is_dir():
            shutil.rmtree(agent_dir, ignore_errors=True)
        return {"deleted": True}
